{
 "title": "流处理任务详情",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "application_ID", "query": "label_values(application)" }
  ]
 },
 "panels": [
  {
   "title": "运行状态",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "streaming_metrics{application=\"$application_ID\",executor_id=\"driver\",qty=\"applicationStatus\",type=\"streaming\"}"
    }
   ]
  },
  {
   "title": "消费线程数",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "streaming_metrics{application=\"$application_ID\",executor_id=\"driver\",qty=\"receivers\",type=\"streaming\"}"
    }
   ]
  },
  {
   "title": "已完成批次",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "streaming_metrics{application=\"$application_ID\",executor_id=\"driver\",qty=\"totalCompletedBatches\",type=\"streaming\"}",
     "legendFormat": "totalCompletedBatches"
    }
   ]
  },
  {
   "title": "已处理记录数",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "streaming_metrics{application=\"$application_ID\",executor_id=\"driver\",qty=\"totalProcessedRecords\",type=\"streaming\"}",
     "legendFormat": "totalProcessedRecords"
    }
   ]
  },
  {
   "title": "记录处理速率概览",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "streaming_metrics{application=\"$application_ID\",executor_id=\"driver\",qty=\"lastCompletedBatch_processRate\",type=\"streaming\"}",
     "legendFormat": "程序处理速率 条/秒"
    },
    {
     "expr": "(rate(streaming_metrics{application=\"$application_ID\",executor_id=\"driver\",qty=\"totalReceivedRecords\",type=\"streaming\"}[5m]))",
     "legendFormat": "接收速率 条/秒"
    },
    {
     "expr": "(increase(streaming_metrics{application=\"$application_ID\",executor_id=\"driver\",qty=\"totalProcessedRecords\",type=\"streaming\"}[5m])) / (5 * 60.0)",
     "legendFormat": "消费速率 条/秒"
    }
   ]
  },
  {
   "title": "单批次耗时：ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 16 },
   "repeat": "application_ID",
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "streaming_metrics{application=\"$application_ID\",executor_id=\"driver\",qty=\"lastCompletedBatch_totalDelay\",type=\"streaming\"}",
     "legendFormat": "总耗时"
    },
    {
     "expr": "streaming_metrics{application=\"$application_ID\",executor_id=\"driver\",qty=\"lastCompletedBatch_processingDelay\",type=\"streaming\"}",
     "legendFormat": "运行耗时"
    },
    {
     "expr": "streaming_metrics{application=\"$application_ID\",executor_id=\"driver\",qty=\"lastCompletedBatch_schedulingDelay\",type=\"streaming\"}",
     "legendFormat": "调度耗时"
    }
   ]
  },
  {
   "title": "批次处理速率 / 分",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(increase(streaming_metrics{application=\"$application_ID\",executor_id=\"driver\",qty=\"totalCompletedBatches\",type=\"streaming\"}[1m])) / 60",
     "legendFormat": "处理速率 批/秒"
    }
   ]
  },
  {
   "title": "单批次记录数量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "streaming_metrics{application=\"$application_ID\",executor_id=\"driver\",qty=\"lastReceivedBatch_records\",type=\"streaming\"}",
     "legendFormat": "最近接收批次记录数"
    },
    {
     "expr": "streaming_metrics{application=\"$application_ID\",executor_id=\"driver\",qty=\"lastCompletedBatch_records\",type=\"streaming\"}",
     "legendFormat": "最近完成批次记录数"
    }
   ]
  },
  {
   "title": "记录数量汇总",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "streaming_metrics{application=\"$application_ID\",executor_id=\"driver\",qty=\"totalReceivedRecords\",type=\"streaming\"}",
     "legendFormat": "接收记录合计"
    },
    {
     "expr": "streaming_metrics{application=\"$application_ID\",executor_id=\"driver\",qty=\"totalProcessedRecords\",type=\"streaming\"}",
     "legendFormat": "处理记录合计"
    }
   ]
  },
  {
   "title": "批次数量汇总",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "streaming_metrics{application=\"$application_ID\",executor_id=\"driver\",qty=\"waitingBatches\",type=\"streaming\"}",
     "legendFormat": "等待批次合计"
    },
    {
     "expr": "streaming_metrics{application=\"$application_ID\",executor_id=\"driver\",qty=\"unprocessedBatches\",type=\"streaming\"}",
     "legendFormat": "未处理批次合计"
    },
    {
     "expr": "streaming_metrics{application=\"$application_ID\",executor_id=\"driver\",qty=\"runningBatches\",type=\"streaming\"}",
     "legendFormat": "运行批次合计"
    }
   ]
  },
  {
   "title": "任务数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(executor_tasks{application=\"$application_ID\", qty!~\"maxPool_size\"}) by (qty)",
     "legendFormat": "{{qty}}"
    }
   ]
  },
  {
   "title": "Driver Heap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_usage{mem_type=\"heap\", qty=\"usage\", application=\"$application_ID\", executor_id=\"driver\"}",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Driver JVM Memory Pools",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools{executor_id=\"driver\", application=\"$application_ID\",qty=\"used\"}",
     "legendFormat": "{{mem_type}}"
    }
   ]
  },
  {
   "title": "Executor Heap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_usage{mem_type=\"heap\", qty=\"usage\", application=\"$application_ID\", executor_id!~\"driver\"} ",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor Eden-Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools{executor_id!~\"driver\", application=\"$application_ID\",qty=\"usage\", mem_type=\"PS-Eden-Space\"}",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor Old-Gen",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools{executor_id!~\"driver\", application=\"$application_ID\",qty=\"usage\", mem_type=\"PS-Old-Gen\"}",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "Executor HDFS reads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "filesystem_usage{qty=\"read_bytes\", fs_type=\"hdfs\", application=\"$application_ID\"}",
     "legendFormat": "{{executor_id}}"
    },
    {
     "expr": "sum(filesystem_usage{qty=\"read_bytes\", fs_type=\"hdfs\", application=\"$application_ID\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "Executor HDFS writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "filesystem_usage{qty=\"write_bytes\", fs_type=\"hdfs\", application=\"$application_ID\"}",
     "legendFormat": "{{executor_id}}"
    }
   ]
  },
  {
   "title": "HDFS Read Rate / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 59 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(filesystem_usage{qty=\"read_bytes\", fs_type=\"hdfs\", application=\"$application_ID\"}[1m]))",
     "legendFormat": "average"
    },
    {
     "expr": "sum(rate(filesystem_usage{qty=\"read_bytes\", fs_type=\"hdfs\", application=\"$application_ID\"}[1m]))",
     "legendFormat": "total"
    }
   ]
  }
 ]
}