{
 "title": "流处理任务概览",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "前一批次数据处理耗时：ms",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "streaming_metrics{executor_id=\"driver\",qty=\"lastCompletedBatch_totalDelay\",type=\"streaming\"}",
     "legendFormat": "{{app_name}}"
    }
   ]
  },
  {
   "title": "批次处理速率 / 分",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "(rate(streaming_metrics{executor_id=\"driver\",qty=\"lastCompletedBatch_processRate\",type=\"streaming\"}[1m]))",
     "legendFormat": "程序处理速率-{{app_name}}"
    }
   ]
  },
  {
   "title": "记录数量汇总",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "streaming_metrics{executor_id=\"driver\",qty=\"totalReceivedRecords\",type=\"streaming\"}",
     "legendFormat": "接收记录合计-{{app_name}}"
    },
    {
     "expr": "streaming_metrics{executor_id=\"driver\",qty=\"totalProcessedRecords\",type=\"streaming\"}",
     "legendFormat": "处理记录合计-{{app_name}}"
    }
   ]
  },
  {
   "title": "任务数",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(executor_tasks{qty!~\"maxPool_size\"}) by (qty)",
     "legendFormat": "{{qty}}"
    }
   ]
  },
  {
   "title": "Driver Heap Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_usage{mem_type=\"heap\", qty=\"usage\", executor_id=\"driver\"}",
     "legendFormat": "{{application}}"
    }
   ]
  },
  {
   "title": "Driver JVM Memory Pools",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pools{executor_id=\"driver\",qty=\"used\"}",
     "legendFormat": "{{mem_type}}"
    }
   ]
  },
  {
   "title": "HDFS Read Rate / s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(rate(filesystem_usage{qty=\"read_bytes\", fs_type=\"hdfs\"}[1m]))",
     "legendFormat": "average-{{application}}"
    },
    {
     "expr": "sum(rate(filesystem_usage{qty=\"read_bytes\", fs_type=\"hdfs\"}[1m]))",
     "legendFormat": "total-{{application}}"
    }
   ]
  }
 ]
}